//数据授权
export const dataAuth = {
  system_manage: 'system manage',
  function_manage: 'menu manage',
  role_manage: 'role manage',
  auth_manage: 'auth manage',
  data_auth: 'auth manage',
  auth_data_group: 'auth group manage',
  role_name:'role name',
  role_code:'role code',
  auth_type:'auth type',
  editroles:'edit roles',
  viewroles:'view roles',
  auth_range:'auth range',
  function_auth:'function auth',
  auth_state:'auth state',
  auth_desp:'description',
  error_domain_tip:'请输入正确的域名!',
  error_appip_count_tip:'每个应用IP数量最多配置为10个,请修正后提交!',
  return:'return',
  rolename_query:'请输入角色名称或编码查询',

  data_auth_insert:"insert",
  role_group:"role group",
  role_person:'role person',
  select_person:'select person',
  organization:'organization',
  person:'person',
  group:'group',
  post:'岗位',
  select_data_rule:'选数据规则',
  data_rule_name:'数据规则名称',
  data_rule_show:'数据规则明细',
  data_rule_code:'数据规则编码',
  auth_description:'授权描述',
  deliver:'交出人',
  receiver:'接收人',
  isDataAuthReplace: '数据权限是否替换',
  useDeliverDataAuth: '使用交出人数据权限',
  repeatSelectDataAuth: '重新选择数据权限',
  // 通用
  pleaseEnter: 'please enter',
  switchuser: 'switch user',
  enterdomainaccount: 'enter domain account',
  appnameorcode: 'app name or code',
  roleameorcode: 'role name or code',
  expand: 'expand',
  yes: 'yes',
  no: 'no',
  basicinfo: 'basic info',
  required: 'required',
  tiprequired: 'tiprequired',
  tips: 'tips',
  createdate: 'create date',
  operation: 'operation',
  mustnum: 'mustnum',
  // menu 轻量级授权
  lightauthor: 'light author',
  usermanage: 'user manage',
  rolemanage: 'role manage',
  rolegroup: 'role group',
  rolegroupCode: 'role group code',
  roleDesp: 'role description',
  organizemanage: 'organize manage',
  functionmanage: 'function manage',
  applicationmanage: 'application manage',
  isAdminroleDesp: 'isAdminroleDesp',
  auditlogmanage: 'auditlogmanage',
  userauth: 'user auth',
  enabled: 'enabled',
  disabled: 'disabled',
  download: "download",
  // 提示
  pleasechooseorgname: 'please choose org name',
  orgnamecannotgroup: '所属组织不能是系统管理组！',
  pleaseselectrecord: '请选择一条记录！',
  ifresetuser: '是否重置用户？',
  currentuserconnot: '当前登录用户不能操作自己的信息！',
  pleaseselectexpired: '请选择已过期的用户进行重置！',
  cancelresetuser: '已取消重置用户！',
  ifunlock: '是否解锁？',
  unlockfail: '解锁失败！',
  cancelresetunlock: '已取消解锁用户！',
  ifresetcommandkey: '是否重置密码？',
  cancelresetcommandkey: '已取消重置密码！',
  ifdelete: '是否删除？',
  deletefail: '删除失败！',
  canceluserdelete: '已取消用户删除！',
  unselectnode: '未选中要保存的节点！',
  oricommandkeyerror: '原始密码输入错误！',
  commandkeynotcomplyrules: '密码必须包含大小写字母、数字、特殊字符、且长度最少12位',
  pleasereenter: '两次输入密码不一致，请重新输入！',
  commandkeychanged: '密码修改成功！',
  failedsave: '保存失败，请检查信息是否完整!',
  userconfigone: '一个用户只能配置一个管理角色!',
  pleasecontact: '配置角色发生异常，请联系管理员！',
  // 用户管理
  username: 'user name',
  usercode: 'user code',
  orgname: 'org name',
  role: 'role',
  state: 'state',
  rolestate: 'role state',
  createby: 'create by',
  more: 'more',
  resetuser: 'reset user',
  unlock: 'unlock',
  resetcommandkey: 'reset commandkey',
  editcommandkey: 'edit commandkey',
  configrole: 'config role',
  businessAuthority: 'business authority',
  expireTime: 'expire time',
  adduser: 'add user',
  edituser: 'edit user',
  originalcommandkey: 'original commandkey',
  newcommandkey: 'new commandkey',
  repeatcommandkey: 'repeat commandkey',
  // 角色管理
  rolename: 'role name',
  rolecode: 'role code',
  roletype: 'role type',
  isAdminRoleDesc: 'isAdminRoleDesc',
  unconfiguredrole: 'unconfigured role',
  configuser: 'config user',
  configorg: 'config org',
  manageauthorize: 'manage authorize',
  businessauthorize: 'business authorize',
  universalAdd: 'Add',
  universalUpdate: 'edit',
  universalDel: 'delete',
  universalQuery: 'query',
  universalImport: 'import',
  universalExport: 'export',
  rolefunction: 'rolefunction',
  supadmnotrole: '管理员不能配置自己角色下的用户！',
  supadmnotorg: '管理员不能配置自己的组织！',
  nonmannotaut: '非管理角色不能做管理授权！',
  noadmincannotconfigrole: '非管理角色不能配置角色！',
  appadminhavenotconfigrole: '应用管理角色无需配置角色！',
  supadmnotaut: '管理员不能配置自己的管理授权！',
  nomanrole: '此用户无管理角色，不允许操作！',
  supadmnotedit: '管理员不能编辑自己的角色！',
  supadmnotdelete: '管理员不能删除自己的角色！',
  appadmnotdelete: '应用管理员角色不能删除！',
  addroles: 'addroles',
  isadminrole: '是否有管理职责',
  superiorrole: '上级角色',
  selsuprole: '请选择上级角色!',
  supbelow: '上级角色不可以为当前角色或当前角色以下的角色!',
  sameroleexist: '存在相同的角色代码，请重新输入角色代码!',
  supasrole: '上级角色不能为自己，请选择其他角色作为上级角色！',
  configuserexcept: '配置用户发生异常，请联系管理员！',
  configusersuccess: '配置用户成功！',
  configorgsuccess: '配置组织发生异常，请联系管理员！',
  selectapplication: 'select application',
  faileobtain: '获取已经授权数据失败，请联系管理员！',
  authorexception: '授权发生异常，请联系管理员！',
  notappadmincannotadd: '非应用管理员不能添加角色',
  notappadmincannotedit: '非应用管理员不能修改角色',
  notappadmincannotdelete: '非应用管理员不能删除角色',
  notappadmincannotdoprivilege: '非应用管理员不能进行管理授权',
  notappadmincannotdobusiprivilege: '非应用管理员不能进行业务授权',
  // 组织管理
  addcompany: 'add company',
  adddepartment: 'add department',
  increasejobs: 'increasejobs',
  showroles: 'show roles',
  showusers: 'show users',
  organizename: 'organize name',
  organizecode: 'organize code',
  sortnumber: 'sort number',
  suporganize: 'suporganize',
  jobname: 'job name',
  jopcode: 'jop code',
  supjob: 'supjob',
  underorgnotdel: '该组织下存在用户，不能删除！',
  underjobnotdel: '该岗位下存在用户，不能删除！',
  // 功能管理
  addfirstlevel: 'add first level',
  functionname: 'function name',
  functiondescript: 'function descript',
  expandFields: 'expand fields',
  functionDataTable: 'function data table',
  functionCode: 'function code',
  urladdress: 'url address',
  nodesorting: 'node sorting',
  isAuthReq: 'isAuthReq',
  functiontype: 'function type',
  universalFunc: 'universal Func',
  menutype: 'menu type',
  log: 'log',
  functionstatus: 'function status',
  superiornode: 'superiornode',
  addfunction: 'add function',
  savenodeaddchild: '请保存该节点，再添加子节点！',
  toplevel: '顶级',
  failparentnode: '获取父节点失败！',
  cannotdelnonleaf: '不能删除非叶子节点，请选择叶子节点进行删除！',
  deletesuccess: '删除成功！',
  deletecancel: '已取消删除！',
  selectnode: 'select node',
  savefailed: 'save failed',
  savesuccess: 'save success',
  verifefail: 'form validate failed!',
  menulocal: '菜单',
  button: 'button',
  webservice: 'web service',
  menulongrange: 'menu long range',
  pc: 'pc',
  mobile: 'mobile',
  available: 'available',
  notavailable: 'not available',
  // 应用管理
  applyid: 'apply id',
  applyname: 'apply name',
  applycode: 'apply code',
  applydomain: 'apply domain',
  applyrootaddress: 'apply root address',
  applyaddresstype: 'apply address type',
  applyAddressStatus: 'apply address status',
  defaulttype: 'default type',
  domaintype: 'domain type',
  applyip: 'apply ip',
  applydescribe: 'apply describe',
  addsystemapply: 'add system apply',
  editsystemapply: 'edit system apply',
  showsystemapply: 'show system apply',
  seconemodify: '请选择一项进行修改！',
  code_valid: '只能是数字，字母，-或者_',
  name_valid: '只能是中文，数字，字母，-或者_',
  url_valid: '只能是数字，字母，/，-或者_',
  languageSet: 'language set',
  setting: 'setting',
  loginTitle: 'login title',
  filter_text: 'filter text',
  waitUser: 'wait user',
  selectUser: 'select user',
  copyFromApp: 'copy function from',
  copyToApp: 'copy function to',
  // 审计日志
  title: 'title',
  businessType: 'business type',
  operName: 'oper name',
  operTime: 'oper time',
  operStatus: 'oper status',
  auditLogDetail: 'audit log detail',
  operModule: 'oper module',
  operUrl: 'oper url',
  operIp: 'oper ip',
  requestMethod: 'request method',
  method: 'method',
  operMsg: 'oper msg',
  operParam: "oper param",
  errorMsg: 'error msg',
  updateState: 'update state',
  queryCon: "condition",
  //数据规则
  data_rule: 'data rule',
  rule_name:'rule name',
  rule_content:'rule content',
  rule_desp:'description',
  //data_statics
  data_auth_statics: 'auth query',
  dataAuth: 'data auth',
  dataRule: 'data rule',
  dataRole: 'data role',
  dataAuthTransfer: 'data auth transfer',
  dataAuthCopy: 'data auth copy',
  personDimension: 'person dimension',
  personName: 'person name',
  roleName: 'role name',
  roleCode: 'role code',
  applyLimit: 'apply limit',
  sourceType: 'source type',
  source: 'source',
  effectLimit: 'effect limit',
  dataDimension: 'data dimension',
  authStatus: 'auth status',
  operate: 'operate',
  personDrillDown: 'personDrillDown',
  roleDimension: 'roleDimension',
  authType: 'auth type',
  authLimit: 'auth limit',
  effectDimension: 'effect dimension',
  authDescribe: 'auth describe',
  roleDrillDown: 'role drill down',
  groupDimension: 'group dimension',
  number: 'num',
  groupName: 'group name',
  groupDescribe: 'group describe',
  groupLimit: 'group limit',
  groupDrillDown: 'group drill down',
  formDimension: 'form dimension',
  branchNumber: 'branch number',
  formName: 'form name',
  authEffect: 'auth effect',
  authDataDimension: 'auth data dimension',
  formDrillDown: 'form drill down',
  postDimension: 'post dimension',
  jobName: 'job name',
  postDrillDown: 'post drill down',
  role: 'role',
  form: 'form',
  job: 'job',
  effectDrillDown: 'effect drillDown',
  roleAuth: 'role auth',
  jobNum: 'job num',
  name: 'name',
  department: 'department',
  dataRuleDetails: 'data rule details',
  dataRuleCode: 'data rule code',
  dataRuleContent: 'data rule content',
  dataRuleName: 'data rule name',
  groupAuth: 'group auth',
  authPerson: 'auth person',
  authForm: 'auth form',
  formCode: 'form code',
  authGroup: 'auth group',
  groupCode: 'group code',
  postCode: 'post code',
  postDescribe: 'post describe',
  isManageRole: 'is manage role',

  isDataAuthReplace: 'is data auth replace',
  useDeliverDataAuth: 'useDeliverDataAuth',
  repeatSelectDataAuth: 'repeatSelectDataAuth',
  rolePost: 'role post',
  dataSource: 'data source',
  postName: 'post name',
  dataAuthMove: 'move',
  nameOrCode: 'name or code',
  staffNo:'staff No',
  chooseFunctionCodeTip : '请先选择功能菜单后再勾选数据规则!',
  /*组管理*/
  group_manage: 'group manage',
  group_name: 'group name',
  group_desc: 'group description',
  group_relation: 'group relation',
  company_name: 'company name',
  org_name: 'org name',
  org_full_name: 'org full name',
  group_type: 'group type',
  person_detail: 'person detail',
  default_option_no: '非默认组项',
  default_option: '默认组项',
  config_group: '配置流程组项',
  group_item_type: '流程组项类型',
  default_select: '默认',
  not_default_select: '非默认',
  select_message: '只能选择公司后才能选择人员和职位！',
  station_message: '双击选中的组织，可以进行职位的刷新！',
  position_information: '职位信息',
  stateion_persons_message: '选择职位后显示职位所属人员',
  company_dialog_title: '选择公司',
  person: 'person',
  name_valid: '只能是中文，数字，字母，-或者_',
  binding: 'binding',
  /*用户管理*/
  user_manage: 'user manage',
  dept_manage: 'dept manage',
  /*选人组件*/
  select_user_name: 'user',
  select_department: 'department',
  select_user_group: 'user group',
  select_route_binding: 'rule',
  select_route_binding_context: '绑定规则表达式',
  select_enter_group_name: 'group name',
  select_all_group: 'all group',
  select_group: 'selected group',
  select_dynamic_role: 'dynamic role',
  select_add_dynamic_role_rule: 'dynamic role rule',
  select_post: 'post',
  select_company: 'company',
  select_position: 'position',
  select_cp_person: 'person',
  select_position: 'position',
  select_position_2: 'position',
  /*用户管理*/
  user_center: 'user center',
  base_info: 'base info',
  permission: 'permission',
  change_pw: "change psw",
  enter_pw_old: "enter old psw",
  enter_pw_new: "enter new psw",
  confirm_pw_new: "confirm psw",
}
