export const config = {
  //配置表管理
  config_table_manage:'配置表管理',
  data_field: '数据有效性',
  data_model: '数据模型',
  auto_write: '自动写入',
  config_name_rule: '只能输入汉字、英文字母、数字以及下划线',
  config_cate: '表单分类',
  version: '版本号',
  add_cate: '新增分类',
  cate_code: '分类编码',
  cate_name: '分类名称',
  parent_dir: '父级目录',
  config_cate_select: '请选择父级数据分类',
  edit_cate: '修改分类',
  config_cate_hasChildren: '数据分类下有数据，不允许删除',
  config_designer: '表单设计器',
  basic_setting: '基础设置',
  release: '发布',
  uploadedFiles :'已上传文档',
  uploadTip:" (仅支持上传txt/doc/docx/pdf/xlsx/xls/格式文档)",
  deleteFile :'删除',
  upgrade: '升版',
  no_upgrade: '不升版',
  is_update: '是否升版本？',
  history: '历史',
  config_components_delete: '确定删除该组件吗？',
  basic_config: '基础配置',
  basic_platform: '基础平台',
  config_category: '配置表分类',
  config_category_search: "搜索分类",
  config_add: "新增配置表",
  config_edit: "修改配置表",
  config_detail: "配置表详情",
  item_manege: "数据项管理",
  config:"配置",
  changeLog:'变更记录',
  cofCode:'配置表编码',
  cofName:'配置表名称',
  tableName:'表名',
  cofTable:'底层数据表名',
  enableDate:'启用日期',
  keyUserId:'原始需求提出人',
  bcId:'需求人员',
  funcDesc:'功能说明',
  cofPath:'配置表URL路径',
  authDesc:'授权说明',
  adminPerson:'管理归口',
  process:'影响的流程范围',
  keyUserPerson:'原始需求提出人',
  developerPerson:'开发需求顾问',
  requirementFile:'对应需求文档',
  cofTempleFile:'配置表模板文件',
  dataRule:'数据规则',
  attentions:'注意事项',
  configDept:"配置方",
  configPerson:"配置人员",
  dataAmount:"数据量",
  retireTime:"退役时间",

  item_config:'字段配置',
  item_name:'字段名称',

  string_type:'字符串类型',
  big_decimal_type:'小数类型',
  integer_type:'整型类型',
  date_type:'日期类型',
  person_type:'人员',
  dept_type:'组织',

  Name: '名称',
  Code: '编码',
  idStrategy: 'ID策略',
  compFieldName: '字段名称',
  compFieldRemark: '字段备注',
  compFieldCode: '字段编码',
  compFieldLength: '字段长度',
  compFieldPoint: '小数点',
  compFieldDefault: '默认值',
  compFieldType: '类型',
  compFieldIsMain: '是否主键',
  compFieldIsNull: '允许空值',
  integrity_tip: ' 行字段属性信息不完整！',
  field_length_tip: ' 行请输入字段长度！',
  field_point_length_tip: ' 行请输入字段长度和小数位长度！',
  field_id_valid_tip_data: '只能是数字，字母，或者_，并且不能以数字开头',
  publish_succ: '发布成功',
  data_item_manage: '数据项管理',
  relate_data_gategory_select: '请选择参数分类！',
  flow_code_valid_no_: '只能包含英文字母和数字，且以英文字母开头。',
  item_default_not_null: '已有数据的情况下，默认值不允许为空',
  dataItemAddDialogTitle: '添加数据项',
  dataItemUpdDialogTitle: '修改数据项',
  code_only_message:'已经存在该分类编码',
  name_only_message:'已经存在该分类名称',
  updateContentCheck:'变更内容不能为空',
  updateReasonCheck:'变更原因不能为空',
  fieldName:'字段名称',
  fieldCode:'字段编码',
  rowName:'行',

  // 配置表日志
  configuration_table_log:'配置表日志',
  operate_log:'操作日志',
  interface_log:'接口日志',
  interface_log_browse:'接口日志一览',
  configName:'配置表名称',
  closeWindow:'关闭',
  dataStatus:'数据状态',
  configOperateName:'配置表操作人姓名',
  configOperate:'配置表操作动作',
  configOperateId:'配置表操作人ID',
  configOperateTime:'配置表操作时间',
  configBeforeContent:'配置表变更前内容',
  configAfterContent:'配置表变更后内容',
  createUserNo:'创建人',
  createUserName:'创建人姓名',
  createDate: '创建时间',
  configLogId:'配置表日志ID',
  begin_time: '开始时间',
  end_time: '结束时间'

}
