
export const dataAuth = {
  system_manage: '应用管理',
  function_manage: '菜单管理',
  role_manage: '角色管理',
  auth_manage: '授权管理',
  data_auth: '授权管理',
  auth_data_group: '授权组管理',
  role_name:'功能角色名称',
  role_code:'功能角色代码',
  auth_type:'授权类型',
  editroles:'编辑角色',
  viewroles:'查看角色',
  auth_range:'授权范围',
  function_auth:'功能权限',
  auth_state:'授权状态',
  auth_desp:'授权描述',
  error_domain_tip:'请输入正确的域名!',
  error_appip_count_tip:'每个应用IP数量最多配置为10个,请修正后提交!',
  return:'返回',
  rolename_query:'请输入角色名称或编码查询',
  begin_time: '生效时间',
  data_auth_insert:"新增授权",
  role_group:"授权角色组",
  role_person:'授权角色',
  select_person:'选择人员',
  organization:'组织',
  person:'人员',
  group:'组',
  post:'岗位',
  select_data_rule:'选数据规则',
  data_rule_name:'数据规则名称',
  data_rule_show:'数据规则明细',
  data_rule_code:'数据规则编码',
  auth_description:'授权描述',
  deliver:'交出人',
  receiver:'接收人',
  isDataAuthReplace: '数据权限是否替换',
  useDeliverDataAuth: '使用交出人数据权限',
  repeatSelectDataAuth: '重新选择数据权限',
  //通用
  pleaseEnter:'请输入',
  switchuser:'切换用户',
  enterdomainaccount:'请输入域帐号',
  appnameorcode:'请输入应用名称或代码',
  roleameorcode:'请输入角色名称或编码',
  expand:'展开',
  yes:'是',
  no:'否',
  basicinfo:'基本信息',
  required:'为必填项',
  tiprequired:'必填',
  tips:'提示',
  createdate:'创建时间',
  operation:'操作',
  mustnum:'请填写数字',
  download:'下载模板',
  select_data: "选择日期",
  select_data_time: "选择日期时间",
  // menu 轻量级授权
  lightauthor:'轻量级授权',
  usermanage:'用户管理',
  rolemanage:'角色管理',
  rolegroup:'功能角色组',
  roleDesp:'功能角色描述',
  organizemanage:'组织管理',
  functionmanage:'功能管理',
  applicationmanage:'应用管理',
  isAdminroleDesp:'是否管理角色',
  auditlogmanage:'审计日志',
  userauth:'用户权限',
  enabled:'正常',
  disabled:'禁用',
  // 提示
  pleasechooseorgname:'请选择所属组织！',
  orgnamecannotgroup:'所属组织不能是系统管理组！',
  pleaseselectrecord:'请选择一条记录！',
  ifresetuser:'是否重置用户？',
  currentuserconnot:'当前登录用户不能操作自己的信息！',
  pleaseselectexpired:'请选择已过期的用户进行重置！',
  cancelresetuser:'已取消重置用户！',
  ifunlock:'是否解锁？',
  unlockfail:'解锁失败！',
  cancelresetunlock:'已取消解锁用户！',
  ifresetcommandkey:'是否重置密码？',
  cancelresetcommandkey:'已取消重置密码！',
  ifdelete:'是否删除？',
  deletefail:'删除失败！',
  canceluserdelete:'已取消用户删除！',
  unselectnode:'未选中要保存的节点！',
  oricommandkeyerror:'原始密码输入错误！',
  commandkeynotcomplyrules:'密码必须包含大小写字母、数字、特殊字符、且长度最少12位',
  pleasereenter:'两次输入密码不一致，请重新输入！',
  commandkeychanged:'密码修改成功！',
  failedsave:'保存失败，请检查信息是否完整!',
  userconfigone:'一个用户只能配置一个管理角色!',
  pleasecontact:'配置角色发生异常，请联系管理员！',
  // 用户管理
  username:'用户名称',
  usercode:'用户编码',
  orgname:'所属组织',
  role:'角色信息',
  state:'当前状态',
  rolestate:'功能角色状态',
  createby:'创建人',
  more:'更多',
  resetuser:'重置用户',
  unlock:'解锁',
  resetcommandkey:'重置密码',
  editcommandkey:'修改密码',
  configrole:'配置角色',
  businessAuthority:'业务权限',
  expireTime:'失效时间',
  adduser:'新增用户',
  edituser:'编辑用户',
  originalcommandkey:'原密码',
  newcommandkey:'新密码',
  repeatcommandkey:'重复密码',
  // 角色管理
  rolename:'角色名称',
  rolecode:'角色代码',
  roletype:'角色类型',
  isAdminRoleDesc:'是否管理角色',
  unconfiguredrole:'选择未配置的角色',
  configuser:'配置用户',
  configorg:'配置组织',
  manageauthorize:'管理授权',
  businessauthorize:'功能授权',
  universalAdd:'新增',
  universalUpdate:'修改',
  universalDel:'删除',
  universalQuery:'查询',
  universalImport:'导入',
  universalExport:'导出',
  rolefunction:'角色权限',
  supadmnotrole:'管理员不能配置自己角色下的用户！',
  supadmnotorg:'管理员不能配置自己的组织！',
  nonmannotaut:'非管理角色不能做管理授权！',
  noadmincannotconfigrole:'非管理角色不能配置角色！',
  appadminhavenotconfigrole:'应用管理角色无需配置角色！',
  supadmnotaut:'管理员不能配置自己的管理授权！',
  nomanrole:'此用户无管理角色，不允许操作！',
  supadmnotedit:'管理员不能编辑自己的角色！',
  supadmnotdelete:'管理员不能删除自己的角色！',
  appadmnotdelete:'应用管理员角色不能删除！',
  addroles:'添加角色',
  isadminrole:'是否有管理职责',
  superiorrole:'上级角色',
  selsuprole:'请选择上级角色!',
  supbelow:'上级角色不可以为当前角色或当前角色以下的角色!',
  sameroleexist:'存在相同的角色代码，请重新输入角色代码!',
  supasrole:'上级角色不能为自己，请选择其他角色作为上级角色！',
  configuserexcept:'配置用户发生异常，请联系管理员！',
  configusersuccess:'配置用户成功！',
  configorgsuccess:'配置组织发生异常，请联系管理员！',
  selectapplication:'选择应用',
  faileobtain:'获取已经授权数据失败，请联系管理员！',
  authorexception:'授权发生异常，请联系管理员！',
  notappadmincannotadd:'非应用管理员不能添加角色',
  notappadmincannotedit:'非应用管理员不能修改角色',
  notappadmincannotdelete:'非应用管理员不能删除角色',
  notappadmincannotdoprivilege:'非应用管理员不能进行管理授权',
  notappadmincannotdobusiprivilege:'非应用管理员不能进行业务授权',
  // 组织管理
  addcompany:'新增公司',
  adddepartment:'新增部门',
  increasejobs:'新增岗位',
  showroles:'角色查询',
  showusers:'人员查询',
  organizename:'组织名称',
  organizecode:'组织代码',
  sortnumber:'排序编号',
  suporganize:'上级组织名称',
  jobname:'岗位名称',
  jopcode:'岗位代码',
  supjob:'上级岗位名称',
  underorgnotdel:'该组织下存在用户，不能删除！',
  underjobnotdel:'该岗位下存在用户，不能删除！',
  // 功能管理
  addfirstlevel:'添加一级菜单',
  functionname:'菜单名称',
  functiondescript:'菜单描述',
  expandFields:'扩展字段',
  functionDataTable:'数据主表名称',
  functionCode:'菜单编码',
  urladdress:'接口地址',
  nodesorting:'节点排序',
  isAuthReq:'是否默认功能',
  functiontype:'菜单类型',
  universalFunc:'通用功能',
  menutype:'菜单类型',
  log:'记录日志',
  functionstatus:'菜单状态',
  superiornode:'上级节点',
  addfunction:'增加功能',
  savenodeaddchild:'请保存该节点，再添加子节点！',
  toplevel:'顶级',
  failparentnode:'获取父节点失败！',
  cannotdelnonleaf:'不能删除非叶子节点，请选择叶子节点进行删除！',
  deletesuccess:'删除成功！',
  deletecancel:'已取消删除！',
  selectnode:'请选择节点！',
  savefailed:'保存失败！',
  savesuccess:'保存成功！',
  verifefail:'表单校验不通过！',
  menulocal:'菜单',
  button:'按钮',
  webservice:'web服务',
  menulongrange:'菜单（远程）',
  pc:'PC端',
  mobile:'移动端',
  available:'可用',
  notavailable:'不可用',
  // 应用管理
  applyid: '应用ID',
  applyname:'应用名称',
  applycode:'应用代码',
  applydomain:'应用域名',
  applyrootaddress:'应用根地址',
  applyaddresstype:'应用地址类型',
  applyAddressStatus: '应用地址状态',
  defaulttype:'默认类型',
  domaintype:'域名类型',
  applyip:'应用IP',
  applydescribe:'应用描述',
  addsystemapply:'新增系统应用',
  editsystemapply:'编辑系统应用',
  showsystemapply:'查看系统应用',
  seconemodify:'请选择一项进行修改！',
  code_valid: '只能是数字，字母，-或者_',
  name_valid: '只能是中文，数字，字母，-或者_',
  url_valid: '只能是数字，字母，/，-或者_',
  languageSet: '其他语言',
  setting: '配置',
  loginTitle: '用户登录',
  filter_text: '输入关键字进行过滤',
  waitUser: '待选用户',
  selectUser: '已选用户',
  copyFromApp: '复制来源应用',
  copyToApp: '复制目标应用',
  // 审计日志
  title: '模块标题',
  businessType: '操作类型',
  operName: '操作人',
  operTime: '操作时间',
  operStatus: '操作状态',
  auditLogDetail:'审计日志详情',
  operModule:'操作模块',
  operUrl:'请求地址',
  operIp:'IP',
  requestMethod:'请求方式',
  method:'操作方法',
  operMsg:'操作内容',
  operParam:"请求参数",
  errorMsg:'异常信息',
  updateState: '更新状态',
  queryCon:"查询条件",
  //数据规则
  data_rule: '数据规则',
  rule_name:'数据规则名称',
  rule_content:'数据规则明细',
  rule_desp:'描述',
  //data_statics
  data_auth_statics: '权限查询',
  dataAuth: '数据授权',
  dataRole:'数据权限',
  dataRule: '数据规则',
  dataAuthTransfer:'授权转移',
  dataAuthCopy: '授权复制',
  personDimension: '人员维度',
  personName: '人员姓名',
  roleName: '角色名称',
  roleCode: '角色代码',
  applyLimit: '应用权限',
  sourceType: '钻取来源类型',
  source: '钻取来源',
  effectLimit: '功能权限',
  dataDimension: '数据维度',
  authStatus: '授权状态',
  operate: '操作',
  personDrillDown: '人员钻取',
  roleDimension: '角色维度',
  authType: '授权类型',
  authLimit: '授权范围',
  effectDimension: '功能维度',
  authDescribe: '授权描述',
  roleDrillDown: '角色钻取',
  groupDimension: '组维度',
  number: '序号',
  groupName: '组名称',
  groupDescribe: '组描述',
  groupLimit: '组范围',
  groupDrillDown: '组钻取',
  formDimension: '组织维度',
  branchNumber: '部门编号',
  formName: '组织名称',
  authEffect: '授权功能',
  authDataDimension: '授权数据维度',
  formDrillDown: '组织钻取',
  postDimension: '岗位维度',
  jobName: '岗位名称',
  postDrillDown: '岗位钻取',
  role: '角色',
  form: '组织',
  job: '岗位',
  effectDrillDown: '功能钻取',
  roleAuth: '角色授权',
  jobNum: '工号',
  name: '姓名',
  department: '所属部门',
  dataRuleDetails: '数据规则明细',
  dataRuleCode: '数据规则代码',
  dataRuleContent:'数据规则内容',
  dataRuleName: '数据规则名称',
  groupAuth: '组授权',
  authPerson: '授权人员',
  authForm: '授权组织',
  formCode: '组织编码',
  authGroup: '授权组',
  groupCode: '组编码',
  postCode: '岗位编码',
  postDescribe: '岗位描述',
  isManageRole: '是否管理角色',
  rolePost:'授权岗位',
  dataSource:'数据来源',
  postName:'岗位名称',

  dataAuthMove:'转移',
  nameOrCode:'角色或编码',
  staffNo:'员工工号',
  chooseFunctionCodeTip : '请先选择功能菜单后再勾选数据规则!',
  /*组管理*/
  group_manage: '组管理',
  group_name: '组名称',
  group_desc: '组描述',
  group_relation: '关联组',
  company_name: '公司名称',
  org_name: '组织名称',
  org_full_name: '组织全称',
  group_type: '组类型',
  person_detail: '人员明细',
  default_option_no: '非默认组项',
  default_option: '默认组项',
  config_group: '配置流程组项',
  group_item_type: '流程组项类型',
  default_select: '默认',
  not_default_select: '非默认',
  select_message: '只能选择公司后才能选择人员和职位！',
  station_message: '双击选中的组织，可以进行职位的刷新！',
  position_information: '职位信息',
  stateion_persons_message: '选择职位后显示职位所属人员',
  company_dialog_title: '选择公司',
  person: '人员',
  name_valid: '只能是中文，数字，字母，-或者_',
  binding: '绑定',
  /*用户管理*/
  user_manage: '用户管理',
  user_id: '员工号',
  user_name: '员工姓名',
  user_name_py: '姓名拼音',
  user_short_py: '拼音简写',
  user_name_eng: '英文名称',
  user_sex: '性别',
  user_status: '状态',
  company_id: '公司编码',
  company_name: '公司',
  user_dept: '部门',
  user_dept_id: '部门id',
  user_dept_code: '部门编码',
  work_dept: '工作部门',
  work_dept_id: '工作部门id',
  work_dept_code: '工作部门编码',
  email: '邮箱',
  cellphone_no: '手机号',
  telephone_no: '座机号',
  contact_address: '办公地址',
  post_code: '邮编',
  user_join_date: '入职时间',
  user_left_date: '离职时间',
  user_ethnic: '民族',
  user_id_card: '身份证',
  user_photo: '照片',
  user_native: '籍贯',
  user_birthday: '出生日期',
  user_maritalstatus: '婚姻状况',
  user_maritalstatus_id: '婚姻状况编号',
  user_pcode: '政治面貌',
  user_pcode_id: '政治面貌编号',
  user_ctr_edu: '学历',
  user_ctr_edu_id: '学历编码',
  user_posi_name: '职位',
  user_posi_id: '职位编码',
  user_dutyrank_name: '职务',
  user_dutyrank_id: '职务编码',
  user_title_name: '职称',
  user_title_new_id: '职称编码',
  user_class_id: '人员类型',
  remark: '备注',
  create_user: '创建人',
  create_date: '创建时间',
  modify_user: '更新人',
  modify_date: '更新时间',
  delete_flag: '删除标识0删除1正常',
  infotype_id: '信息来源编码',
  /*部门管理*/
  dept_manage: '组织管理',
  /*选人组件*/
  select_user_name: '用户',
  select_department: '组织',
  select_user_group: '用户组',
  select_route_binding: '绑定规则',
  select_route_binding_context: '绑定规则表达式',
  select_enter_group_name: '请输入组名称',
  select_all_group: '全部组',
  select_group: '已选组',
  select_dynamic_role: '动态角色',
  select_add_dynamic_role_rule: '添加动态角色规则',
  select_post: '岗位/职位',
  select_company: '选择公司',
  select_position: '选择职位',
  select_cp_person: '对应人员',
  select_position: '职位',
  select_position_2: '岗位',
  /*用户管理*/
  user_center: '用户中心',
  base_info: '基本信息',
  permission: '权限查询',
  change_pw: "修改密码",
  enter_pw_old: "请输入旧密码",
  enter_pw_new: "请输入新密码",
  confirm_pw_new: "请确认新密码",
}
